### ISSUE TITLE
Cert generation fails because deploy_cert accepts too few arguments

### ISSUE THREAD

**Issue by jbyauk** [e00E/lets-encrypt-icecast#1]
I am trying to using this plugin to generate a letsencrypt certificate for my Icecast 2 installation, but when I run the certificate generation command, I get an error message:

lets-encrypt-icecast setup commands:
```
git clone https://github.com/letsencrypt/letsencrypt.git
git clone https://github.com/e00E/lets-encrypt-icecast.git
cd letsencrypt
./tools/venv.sh
./venv/bin/python ../lets-encrypt-icecast/setup.py develop
cp ../lets-encrypt-icecast/icecast.py .
./venv/bin/lets	encrypt --help all
```

Code:
```
sudo ./venv/bin/letsencrypt -t -i letsencrypt-icecast:icecast_installer run
```

Error:
```
An unexpected error occurred:
BrokenMethodImplementation: The implementation of deploy_cert violates its contract
        because implementation doesn't allow enough arguments.

Please see the logfiles in /var/log/letsencrypt for more details.
```

Log details:
```
2016-03-02 20:25:18,173:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-03-02 20:25:18,173:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-03-02 20:25:18,173:DEBUG:letsencrypt.cli:letsencrypt version: 0.5.0.dev0
2016-03-02 20:25:18,173:DEBUG:letsencrypt.cli:Arguments: ['-t', '-i', 'letsencrypt-icecast:icecast_installer']
2016-03-02 20:25:18,173:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#nginx,PluginEntryPoint#letsencrypt-icecast:icecast_installer,PluginEntryPoint#null,PluginEntryPoint#apache)
2016-03-02 20:25:18,174:DEBUG:letsencrypt.cli:Requested authenticator None and installer letsencrypt-icecast:icecast_installer
2016-03-02 20:25:18,179:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "./venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt', 'console_scripts', 'letsencrypt')()
  File "/home/ubuntu/letsencrypt/letsencrypt/cli.py", line 1993, in main
    return config.func(config, plugins)
  File "/home/ubuntu/letsencrypt/letsencrypt/cli.py", line 654, in run
    installer, authenticator = choose_configurator_plugins(config, plugins, "run")
  File "/home/ubuntu/letsencrypt/letsencrypt/cli.py", line 627, in choose_configurator_plugins
    installer = display_ops.pick_installer(config, req_inst, plugins)
  File "/home/ubuntu/letsencrypt/letsencrypt/display/ops.py", line 125, in pick_installer
    config, default, plugins, question, (interfaces.IInstaller,))
  File "/home/ubuntu/letsencrypt/letsencrypt/display/ops.py", line 91, in pick_plugin
    verified = filtered.verify(ifaces)
  File "/home/ubuntu/letsencrypt/letsencrypt/plugins/disco.py", line 209, in verify
    return self.filter(lambda p_ep: p_ep.verify(ifaces))
  File "/home/ubuntu/letsencrypt/letsencrypt/plugins/disco.py", line 196, in filter
    in self._plugins.iteritems() if pred(plugin_ep)))
  File "/home/ubuntu/letsencrypt/letsencrypt/plugins/disco.py", line 196, in <genexpr>
    in self._plugins.iteritems() if pred(plugin_ep)))
  File "/home/ubuntu/letsencrypt/letsencrypt/plugins/disco.py", line 209, in <lambda>
    return self.filter(lambda p_ep: p_ep.verify(ifaces))
  File "/home/ubuntu/letsencrypt/letsencrypt/plugins/disco.py", line 82, in verify
    zope.interface.verify.verifyObject(iface, self.init())
  File "/home/ubuntu/letsencrypt/venv/local/lib/python2.7/site-packages/zope/interface/verify.py", line 105, in verifyObject
    return _verify(iface, candidate, tentative, vtype='o')
  File "/home/ubuntu/letsencrypt/venv/local/lib/python2.7/site-packages/zope/interface/verify.py", line 97, in _verify
    raise BrokenMethodImplementation(name, mess)
BrokenMethodImplementation: The implementation of deploy_cert violates its contract
        because implementation doesn't allow enough arguments.
```

**Comment by e00E** [comment]
Should be fixed, however I currently dont have a working icecast or letsencrypt installation so I am not 100% sure.
